[build-system]
requires = ["setuptools>=64", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"


[project]
name = "biomero-importer"
dynamic = ["version"]
description = "BIOMERO.importer - Automated Data Import System (formerly OMERO ADI)"
authors = [{ name = "Core Facility - Cellular Imaging", email = "cellularimaging@amsterdamumc.nl" }]
license = { file = "LICENSE" }
requires-python = ">=3.11"
readme = "README.md"  
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: GNU General Public License v2 (GPLv2)",
    "Operating System :: OS Independent",
]
dependencies = [
    "ezomero==3.2.3",
    "pandas>=2.2.1",
    "numpy>=1.26.4",
    "openpyxl>=3.1.2",
    "python-dotenv>=1.0.1",
    "pytest>=8.2.1",
    "sqlalchemy>=2.0.28",
    "psycopg2>=2.9.7",
    "zarr>=3",
    "alembic>=1.13",
    "biomero-schema>=0.2.1.dev1,<0.3",
    "biomero-shallower==0.1.0"
]

[project.optional-dependencies]
test = [
    "pytest-cov",
    "mock",
    "psycopg2-binary"
]
identity = [
    "iscc-bio[ome-zarr]>=0.2,<0.3"
]

[tool.setuptools.packages]
find = {}  # Scan the project directory with the default parameters

[tool.setuptools_scm]
write_to = "biomero_importer/_version.py"

[project.urls]
"Homepage" = "https://github.com/Cellular-Imaging-Amsterdam-UMC/BIOMERO.importer"
"Documentation" = "https://cellular-imaging-amsterdam-umc.github.io/NL-BIOMERO/"
"Repository" = "https://github.com/Cellular-Imaging-Amsterdam-UMC/BIOMERO.importer"

[tool.pytest.ini_options]
cache_dir = "/tmp/.pytest_cache"

[tool.setuptools.package-data]
biomero_importer = ["migrations/**", "migrations/versions/**"]
