"""add description to imports

Revision ID: 78d3d6d84aec
Revises: 
Create Date: 2025-08-25 16:10:58.635476
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d3d6d84aec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imports', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imports', 'description')
    # ### end Alembic commands ###
